[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
 name = "Profiel"
 url = "profiel/"
 weight = -107

[[main]]
  name = "About"
  url = "about/"
  weight = -109

# Submenus are done this way: parent -> identifier
# [[main]]
#   name = "Category"
#   identifier = "Links"
#   weight = -106
# [[main]]
#   parent = "Links"
#   name = "プログラミング"
#   url = "https://www.linkedin.com/"
# [[main]]
#   parent = "Links"
#   name = "その他"
#   url = "https://twitter.com/"


# social menu links
[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/tamaki380"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/TmgHiro"
# [[social]]
#   name = "linkedin"
#   weight = 3
#   url = "https://www.linkedin.com/in/#"
# [[social]]
#   name = "rss"
#   weight = 4
#   url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"