[ja]
  title = "Clarity"
  LanguageName = "japanese"
  weight = 1

# [en]
#   title = "Clarity"
#   LanguageName = "English"
#   weight = 2

# [pt]
#   title = "Claridade" # just for the sake of showing this is possible
#   LanguageName = "Português"
#   weight = 3

  # tip: assign the default language the lowest Weight